[GLOBAL]
pants_version = "2.19.0.dev4"

plugins = ["hdrhistogram"]

backend_packages = [
  "pants.backend.shell",
]

remote_cache_read = true
remote_cache_write = true
remote_instance_name = "huge"

[source]
root_patterns = [
  "/",
]

[python]
interpreter_constraints = ["==3.9.*"]

[stats]
log = true

[anonymous-telemetry]
enabled = false
