[GLOBAL]
pants_version = "2.19.0a0"

plugins = ["hdrhistogram"]

backend_packages = [
  "pants.backend.shell",
]

# run more of these low-effort processes at a time even on the two core GHA runners
process_execution_local_parallelism = 20

remote_cache_read = true
remote_cache_write = true
remote_instance_name = "huge"

# remote_store_rpc_concurrency = 1

[source]
root_patterns = [
  "/",
]

[python]
interpreter_constraints = ["==3.9.*"]

[stats]
log = true

[anonymous-telemetry]
enabled = false
