---
name: App

"on":
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: code

      - uses: actions/checkout@v3
        with:
          repository: "pantsbuild/pants"
          #ref: "feature/other-remote-caches"
          path: pants

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - run: |
          env

        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
          CONTEXT_ENV: ${{ toJSON(env) }}
          CONTEXT_RUNNER: ${{ toJSON(runner) }}
          CONTEXT_SECRETS: ${{ toJSON(secrets) }}

      - name: Configure pants env vars
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('PANTS_REMOTE_GHA_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('PANTS_REMOTE_GHA_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Cache Rust compilation
        uses: metalbear-co/sccache-action@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          ./pants_from_sources -ldebug version
        working-directory: code

      - run: |
          ./pants_from_sources -ldebug test ::
        working-directory: code
