---
name: App

"on":
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          ./get-pants.sh
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Configure pants env vars
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('PANTS_REMOTE_PROVIDER', 'experimental-github-actions-cache');
            core.exportVariable('PANTS_REMOTE_STORE_ADDRESS', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('PANTS_REMOTE_OAUTH_BEARER_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - run: |
          pants test ::
