---
name: App

"on":
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: code

      - uses: actions/checkout@v3
        with:
          repository: "pantsbuild/pants"
          ref: "huonw/11149-ghac"
          path: pants

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - name: "Install Protoc"
        uses: "arduino/setup-protoc@9b1ee5b22b0a3f1feb8c2ff99b32c89b3c3191e9"
        with:
          version: "23.x"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - run: |
          curl --proto '=https' --tlsv1.2 -fsSL https://static.pantsbuild.org/setup/get-pants.sh | bash
          echo $HOME/bin >> $GITHUB_PATH
          env

        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
          CONTEXT_ENV: ${{ toJSON(env) }}
          CONTEXT_RUNNER: ${{ toJSON(runner) }}
          CONTEXT_SECRETS: ${{ toJSON(secrets) }}

      - name: Configure pants env vars
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Cache Rust compilation
        uses: metalbear-co/sccache-action@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          MODE=debug PANTS_SOURCE=../pants pants -ldebug version
        working-directory: code

      - run: |
          MODE=debug PANTS_SOURCE=../pants pants -ldebug test ::
        working-directory: code
